version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  commit_master:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install --upgrade pip setuptools wheel
            pyenv install 3.6.15
            pyenv install 3.7.12
            pyenv install 3.8.12
            pyenv versions
            pyenv local 3.6 3.7 3.8 3.9
            pip install --upgrade tox tox-pyenv
            make dev
      - run:
          name: Run all tests
          command: make tox
