version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  commit_master:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: rstms/python-hydra:1.0.0
    steps:
      - checkout
      - run:
          name: configure python versions
          command: |
            pwd
            echo PATH=$PATH
            ls -al /home/hydra
            cat /home/hydra/.bashrc
            set
            pyenv local system
            pyenv local $(echo $(for V in $(seq 6 9); do (pyenv versions | grep "3\.${V}\."); done))
            pyenv local
            python3.6 --version
            python3.7 --version
            python3.8 --version
            python3.9 --version
      - run:
          name: activate install dependencies
          command: |
            pwd
            echo PATH=$PATH
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools wheel
            make dev
            pip install --upgrade tox-pyenv
      - run:
          name: Run all tests
          command: |
            pwd
            echo PATH=$PATH
            . venv/bin/activate
            make tox
