version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  commit_master:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dev dependencies 
          command: |
            make dev
            pip install tox tox-pyenv
            pyenv local 3.6 3.7 3.8 3.9
      - run:
          name: Run all tests
          command: make tox
