version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  commit_master:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: rstms/python-hydra:1.0.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools wheel
            make dev
            pip install --upgrade tox-pyenv
            pyenv local $(echo $(for V in $(seq 6 9); do (pyenv versions | grep " *3.${V}\." | tail -1); done))
            pyenv local
      - run:
          name: Run all tests
          command: make tox
